// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: failures.sql

package db

import (
	"context"
	"net/netip"

	"time"
)

const countFailures = `-- name: CountFailures :one
SELECT count(*) FROM auth_failures WHERE scope = $1 AND network = $2 AND failed_at > now() - $3::interval
`

type CountFailuresParams struct {
	Scope   string
	Network netip.Prefix
	Period  time.Duration
}

func (q *Queries) CountFailures(ctx context.Context, arg CountFailuresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailures, arg.Scope, arg.Network, arg.Period)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldFailures = `-- name: DeleteOldFailures :exec
DELETE FROM auth_failures WHERE scope = $1 AND failed_at <= now() - $2::interval
`

type DeleteOldFailuresParams struct {
	Scope  string
	Period time.Duration
}

func (q *Queries) DeleteOldFailures(ctx context.Context, arg DeleteOldFailuresParams) error {
	_, err := q.db.Exec(ctx, deleteOldFailures, arg.Scope, arg.Period)
	return err
}

const recordFailure = `-- name: RecordFailure :exec
INSERT INTO auth_failures (scope, network) VALUES ($1, $2)
`

type RecordFailureParams struct {
	Scope   string
	Network netip.Prefix
}

func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure, arg.Scope, arg.Network)
	return err
}
