// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UserAgent  string
	LastSeenAt time.Time
	LastSeenIp *netip.Addr
}
