// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countUserSessions = `-- name: CountUserSessions :one
SELECT count(*) AS total, count(*) FILTER (WHERE token_hash <> $1) AS others
FROM sessions
WHERE user_id = $2 AND expires_at > now() AND ($3::text = '' OR strpos(host(last_seen_ip), lower($3::text)) > 0)
`

type CountUserSessionsParams struct {
	CurrentHash []byte
	UserID      uuid.UUID
	Ip          string
}

type CountUserSessionsRow struct {
	Total  int64
	Others int64
}

func (q *Queries) CountUserSessions(ctx context.Context, arg CountUserSessionsParams) (CountUserSessionsRow, error) {
	row := q.db.QueryRow(ctx, countUserSessions, arg.CurrentHash, arg.UserID, arg.Ip)
	var i CountUserSessionsRow
	err := row.Scan(&i.Total, &i.Others)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at, user_agent, last_seen_ip) VALUES ($1, $2, $3, $4, $5) RETURNING id, token_hash, user_id, expires_at, created_at, user_agent, last_seen_at, last_seen_ip
`

type CreateSessionParams struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	UserAgent  string
	LastSeenIp *netip.Addr
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.LastSeenIp,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.LastSeenIp,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const endOtherUserSessions = `-- name: EndOtherUserSessions :execrows
DELETE FROM sessions
WHERE user_id = $1 AND token_hash <> $2 AND expires_at > now() AND ($3::text = '' OR strpos(host(last_seen_ip), lower($3::text)) > 0)
`

type EndOtherUserSessionsParams struct {
	UserID      uuid.UUID
	CurrentHash []byte
	Ip          string
}

func (q *Queries) EndOtherUserSessions(ctx context.Context, arg EndOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endOtherUserSessions, arg.UserID, arg.CurrentHash, arg.Ip)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endUserSessions = `-- name: EndUserSessions :execrows
DELETE FROM sessions
WHERE user_id = $1 AND id = ANY($2::uuid[]) AND token_hash <> $3 AND expires_at > now()
`

type EndUserSessionsParams struct {
	UserID      uuid.UUID
	Ids         []uuid.UUID
	CurrentHash []byte
}

func (q *Queries) EndUserSessions(ctx context.Context, arg EndUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endUserSessions, arg.UserID, arg.Ids, arg.CurrentHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_agent, created_at, last_seen_at, last_seen_ip, token_hash = $1 AS is_current
FROM sessions
WHERE user_id = $2 AND expires_at > now() AND ($3::text = '' OR strpos(host(last_seen_ip), lower($3::text)) > 0)
ORDER BY
    CASE WHEN $4::text = 'createdAt' AND $5::bool = false THEN created_at END,
    CASE WHEN $4::text = 'createdAt' AND $5::bool THEN created_at END DESC,
    CASE WHEN $4::text = 'lastSeenAt' AND $5::bool = false THEN last_seen_at END,
    CASE WHEN $4::text = 'lastSeenAt' AND $5::bool THEN last_seen_at END DESC,
    id
LIMIT $7::bigint OFFSET $6::bigint
`

type ListUserSessionsParams struct {
	CurrentHash []byte
	UserID      uuid.UUID
	Ip          string
	SortBy      string
	Descending  bool
	RowOffset   int64
	RowLimit    int64
}

type ListUserSessionsRow struct {
	ID         uuid.UUID
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	LastSeenIp *netip.Addr
	IsCurrent  bool
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions,
		arg.CurrentHash,
		arg.UserID,
		arg.Ip,
		arg.SortBy,
		arg.Descending,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.LastSeenIp,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionByTokenHash = `-- name: SessionByTokenHash :one
SELECT id, token_hash, user_id, expires_at, created_at, user_agent, last_seen_at, last_seen_ip FROM sessions WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) SessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.LastSeenIp,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), last_seen_ip = coalesce($1::inet, last_seen_ip) WHERE id = $2
`

type TouchSessionParams struct {
	LastSeenIp *netip.Addr
	ID         uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastSeenIp, arg.ID)
	return err
}
