import { Linter, RuleTester } from 'eslint';
import tseslint from 'typescript-eslint';
import { describe, expect, it } from 'vitest';
import { listLayout } from '../../../tools/eslint/listLayout/listLayout';

RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const languageOptions = { parser: tseslint.parser };

const tester = new RuleTester({ languageOptions });

const lines = (...rows: string[]): string => rows.join('\n');

const a = 'a'.repeat(24);

const b = 'b'.repeat(24);

const c = 'c'.repeat(24);

tester.run('list-layout', listLayout, {
    valid: [
        `const point = { ${a}: 1 };`,
        lines('const point = {', '    x: 1,', '    y: 2,', '};'),
        lines('const pair = [', `    'x',`, '    1,', '];'),
        lines('type Point = {', '    x: number;', '};'),
        lines(`send(${a}, ${b}, {`, '    x: 1,', '    y: 2,', '});'),
        lines(`describe('the list', () => {`, '    run();', '});'),
        lines('setTimeout(() => {', '    run();', '}, 100);'),
        lines(`const rule = ['error', {`, `    prefer: 'type-imports',`, `    fixStyle: 'inline',`, '}];'),
        lines('const parts = [{', `    type: 'arg',`, `    name: 'name',`, '}];'),
        lines('const make = (props: {', '    x?: string;', '    y?: number;', '}): void => undefined;'),
        'send(1, 2);',
        'const { form, errors } = use();',
        'type Pair = [string, number];',
        `const pound = { type: 'pound' } as const;`,
        lines('const point = {', '    x: 1, // the first', '};'),
        lines('// Code generated by a tool. DO NOT EDIT.', 'const point = { x: 1, y: 2 };'),
    ],
    invalid: [
        {
            code: lines('const point = {', `    ${a}: 1,`, '};'),
            output: `const point = { ${a}: 1 };`,
            errors: [{ messageId: 'collapse' }],
        },
        {
            code: lines('send(1,', '    2);'),
            output: 'send(1, 2);',
            errors: [{ messageId: 'collapse' }],
        },
        {
            code: 'const point = { x: 1, y: 2 };',
            output: lines('const point = {', '    x: 1,', '    y: 2,', '};'),
            errors: [{ messageId: 'object' }],
        },
        {
            code: `const pair = ['x', 1];`,
            output: lines('const pair = [', `    'x',`, '    1,', '];'),
            errors: [{ messageId: 'array' }],
        },
        {
            code: 'type Point = { x: number; y: number };',
            output: lines('type Point = {', '    x: number;', '    y: number;', '};'),
            errors: [{ messageId: 'type' }],
        },
        {
            code: 'type Point = { x: number };',
            output: lines('type Point = {', '    x: number;', '};'),
            errors: [{ messageId: 'type' }],
        },
        {
            code: 'type Route = Base & { path: string };',
            output: lines('type Route = Base & {', '    path: string;', '};'),
            errors: [{ messageId: 'type' }],
        },
        {
            code: `const rule = ['error', { prefer: 'type-imports', fixStyle: 'inline' }];`,
            output: lines(`const rule = ['error', {`, `    prefer: 'type-imports',`, `    fixStyle: 'inline',`, '}];'),
            errors: [
                { messageId: 'array' },
                { messageId: 'object' },
            ],
        },
        {
            code: `const rule = ['error', { strict: true }];`,
            output: lines('const rule = [', `    'error',`, '    { strict: true },', '];'),
            errors: [{ messageId: 'array' }],
        },
        {
            code: 'export const router = createRouter({ history: createWebHistory(), routes });',
            output: lines(
                'export const router = createRouter({',
                '    history: createWebHistory(),',
                '    routes,',
                '});',
            ),
            errors: [{ messageId: 'object' }],
        },
        {
            code: `json({ id: 1, email: 'x' }, 200);`,
            output: lines('json({', '    id: 1,', `    email: 'x',`, '}, 200);'),
            errors: [{ messageId: 'object' }],
        },
        {
            code: lines(
                'const make = (',
                '    props: {',
                '        x?: string;',
                '        y?: number;',
                '    },',
                '): void => undefined;',
            ),
            output: lines('const make = (props: {', '    x?: string;', '    y?: number;', '}): void => undefined;'),
            errors: [{ messageId: 'hugLast' }],
        },
        {
            code: lines('send(', `    ${a},`, '    {', '        x: 1,', '        y: 2,', '    },', ');'),
            output: lines(`send(${a}, {`, '    x: 1,', '    y: 2,', '});'),
            errors: [{ messageId: 'hugLast' }],
        },
        {
            code: lines('setTimeout(', '    () => {', '        run();', '    },', '    100,', ');'),
            output: lines('setTimeout(() => {', '    run();', '}, 100);'),
            errors: [{ messageId: 'hugFirst' }],
        },
        {
            code: lines(
                `const result = await send<${a}, ${b}, ${c}>('POST', '/path', {`,
                '    x: 1,',
                '    y: 2,',
                '});',
            ),
            output: lines(
                `const result = await send<${a}, ${b}, ${c}>(`,
                `    'POST',`,
                `    '/path',`,
                '    {',
                '        x: 1,',
                '        y: 2,',
                '    },',
                ');',
            ),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: `const value = first(${a}, ${b}).second(${c}, ${a});`,
            output: lines(`const value = first(${a}, ${b}).second(`, `    ${c},`, `    ${a},`, ');'),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: `expect(format(${a}, ${b}, ${c}, ${a})).toBe('done');`,
            output: lines('expect(', `    format(${a}, ${b}, ${c}, ${a}),`, `).toBe('done');`),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: `const send = (${a}: string, ${b}: number, ${c}: Map<string, number>): void => undefined;`,
            output: lines(
                'const send = (',
                `    ${a}: string,`,
                `    ${b}: number,`,
                `    ${c}: Map<string, number>,`,
                '): void => undefined;',
            ),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: `import { ${a}, ${b}, ${c}, ${a}2, type Other } from 'module';`,
            output: lines(
                'import {',
                `    ${a},`,
                `    ${b},`,
                `    ${c},`,
                `    ${a}2,`,
                '    type Other,',
                `} from 'module';`,
            ),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: `const { ${a}, ${b}, ${c}, ${a}2, ...rest } = source;`,
            output: lines('const {', `    ${a},`, `    ${b},`, `    ${c},`, `    ${a}2,`, '    ...rest', '} = source;'),
            errors: [{ messageId: 'expand' }],
        },
        {
            code: lines(`send(${a}, ${b}, ${c}, ${a}, \``, 'line`);'),
            output: null,
            errors: [{ messageId: 'expand' }],
        },
    ],
});

describe('the fixes of list-layout', () => {
    it('settle on the layout of the rule after several passes', () => {
        const linter = new Linter({ configType: 'flat' });
        const config = {
            files: ['**/*.ts'],
            languageOptions,
            plugins: { codestyle: { rules: { 'list-layout': listLayout } } },
            rules: { 'codestyle/list-layout': 'error' as const },
        };
        const code = `expect(rows).toEqual([['x', 1], ['y', 2]]);`;

        expect(linter.verifyAndFix(code, [config], { filename: 'file.ts' }).output).toBe(
            lines(
                'expect(rows).toEqual([',
                '    [',
                `        'x',`,
                '        1,',
                '    ],',
                '    [',
                `        'y',`,
                '        2,',
                '    ],',
                ']);',
            ),
        );
    });
});
