// Code generated by tsgen. DO NOT EDIT.

import { isRecord, isString } from '@/shared/TypeGuards/typeGuards';

export type CurrentUser = {
    id: string;
    email: string;
};

export const isCurrentUser = (v: unknown): v is CurrentUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['email']);
