// Code generated by tsgen. DO NOT EDIT.

import { isApiFieldErrors } from '@/shared/Fetch/Envelope/ApiFieldErrors';
import type { ApiMessage } from '@/shared/Fetch/Envelope/ApiMessage';

export type LocaleRequest = {
    locale: string;
};

export type LocaleRequestErrors = {
    general?: ApiMessage;
    locale?: ApiMessage;
};

export const isLocaleRequestErrors = (v: unknown): v is LocaleRequestErrors =>
    isApiFieldErrors(/^(?:general|locale)$/, v);
