// Code generated by tsgen. DO NOT EDIT.

export const ScriptURL = {
    GoogleTag: 'https://www.googletagmanager.com/gtag/js',
    MetaPixel: 'https://connect.facebook.net/en_US/fbevents.js',
} as const;

export type ScriptURL = (typeof ScriptURL)[keyof typeof ScriptURL];

export const isScriptURL = (v: unknown): v is ScriptURL =>
    Object.values(ScriptURL).some((value) => value === v);
