// Code generated by tsgen. DO NOT EDIT.

export const TrustedTypesPolicy = {
    ScriptLoader: 'script-loader',
} as const;

export type TrustedTypesPolicy = (typeof TrustedTypesPolicy)[keyof typeof TrustedTypesPolicy];

export const isTrustedTypesPolicy = (v: unknown): v is TrustedTypesPolicy =>
    Object.values(TrustedTypesPolicy).some((value) => value === v);
