// Code generated by i18n. DO NOT EDIT.

import type { DictionarySource } from '@/shared/I18n/Dictionary/types/DictionarySource';

export const dictionaries: Readonly<Record<string, DictionarySource>> = {
    cs_CZ: { version: '2f5dbecb3820c5d5', name: 'Čeština', load: async () => (await import('@/shared/I18n/Dictionary/Locales/cs_CZ')).dictionary },
    en_US: { version: '366762adf139ea51', name: 'English', load: async () => (await import('@/shared/I18n/Dictionary/Locales/en_US')).dictionary },
};
