// Code generated by tsgen. DO NOT EDIT.

export const ApiMessageKey = {
    InvalidBody: 'request.invalid_body',
    BodyTooLarge: 'request.body_too_large',
    Internal: 'request.internal',
    InvalidQuery: 'request.invalid_query',
    Required: 'validation.required',
    Email: 'validation.email',
    UUID: 'validation.uuid',
    MinLength: 'validation.min_length',
    MaxLength: 'validation.max_length',
    MinItems: 'validation.min_items',
    MaxItems: 'validation.max_items',
    Min: 'validation.min',
    Max: 'validation.max',
    OneOf: 'validation.one_of',
    Invalid: 'validation.invalid',
    SignInRequired: 'auth.sign_in_required',
    TooManyAttempts: 'request.too_many_attempts',
    LoginFailed: 'auth.login_failed',
    EmailTaken: 'user.email_taken',
    NotFound: 'request.not_found',
} as const;

export type ApiMessageKey = (typeof ApiMessageKey)[keyof typeof ApiMessageKey];

export const isApiMessageKey = (v: unknown): v is ApiMessageKey =>
    Object.values(ApiMessageKey).some((value) => value === v);
