// Code generated by tsgen. DO NOT EDIT.

import { isRecord, isString } from '@/shared/TypeGuards/typeGuards';

export type SessionUser = {
    id: string;
};

export const isSessionUser = (v: unknown): v is SessionUser =>
    isRecord(v)
    && isString(v['id']);
