package noalign

import (
	"go/format"
	"os"
	"path/filepath"
	"testing"

	"gokick/tools/codestyle/gofiles"
)

func TestFindsColumns(t *testing.T) {
	tests := []struct {
		name, src string
	}{
		{"struct fields", "type T struct {\n\tname string\n\tproxies []string\n}\n"},
		{"multi-line keyed literal", "var v = T{\n\tname: \"x\",\n\tproxies: nil,\n}\n"},
		{"const block", "const (\n\ta = 1\n\tlonger = 2\n)\n"},
		{"trailing comments", "func f() {\n\tx := 1 // one\n\tyyyyyy := 2 // two\n\t_, _ = x, yyyyyy\n}\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if issues := check(t, tt.src); len(issues) == 0 {
				t.Errorf("no column found in\n%s", gofmt(t, tt.src))
			}
		})
	}
}

func TestLeavesColumnFreeCodeAlone(t *testing.T) {
	tests := []struct {
		name, src string
	}{
		{"fields split by blank lines", "type T struct {\n\tName string\n\n\tTrustedProxies []string\n}\n"},
		{"one-line keyed literals", "var v = []T{\n\t{name: \"Cloudflare\", proxies: nil},\n\t{name: \"b\", proxies: []string{\"10.0.0.0/8\"}},\n}\n"},
		{"spaces inside strings and comments", "var s = \"a    b\" // c    d\n\nvar r = `\n  e    f\n`\n"},
		{"block comment over lines", "/* a\n    b */\nvar x = 1\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if issues := check(t, tt.src); len(issues) != 0 {
				t.Errorf("unexpected %v in\n%s", issues, gofmt(t, tt.src))
			}
		})
	}
}

func TestColumnsSkipsGeneratedFilesAndTestdata(t *testing.T) {
	root := t.TempDir()
	aligned := gofmt(t, "type T struct {\n\tname string\n\tproxies []string\n}\n")
	write(t, filepath.Join(root, "gen.go"), "// Code generated by sqlc. DO NOT EDIT.\n\n"+aligned)
	write(t, filepath.Join(root, "testdata", "fixture.go"), aligned)
	write(t, filepath.Join(root, "sub", "hand.go"), aligned)

	issues, err := Issues(root)
	if err != nil {
		t.Fatal(err)
	}

	if len(issues) != 1 || issues[0].Pos.Filename != filepath.Join(root, "sub", "hand.go") {
		t.Errorf("got %v, want one issue in sub/hand.go", issues)
	}
}

func check(t *testing.T, src string) []gofiles.Issue {
	t.Helper()

	return Find("case.go", []byte(gofmt(t, src)))
}

func gofmt(t *testing.T, src string) string {
	t.Helper()

	out, err := format.Source([]byte("package p\n\n" + src))
	if err != nil {
		t.Fatal(err)
	}

	return string(out)
}

func write(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}
