package typescript

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"slices"
	"strings"

	"gokick/app/core/i18n/icu"
	"gokick/locale"
	"gokick/tools/codegen"
	"gokick/tools/i18n/dictionaries"
)

const Header = "// Code generated by i18n. DO NOT EDIT.\n"

const versionBytes = 8

var ErrLanguageName = errors.New("a dictionary has no " + locale.NameKey + " of plain text")

type source struct {
	version string

	name string
}

func Render(c dictionaries.Catalog) (codegen.Files, error) {
	content := map[string][]byte{locale.TypeScriptDir + "/MessageParams.ts": params(c)}
	sources := map[string]source{}

	for _, l := range c.Locales {
		name, ok := plainText(l.Messages[locale.NameKey])
		if ok == false || name == "" {
			return codegen.Files{}, fmt.Errorf("%w: %s", ErrLanguageName, l.Name)
		}

		module := dictionary(c.Keys, l)
		sum := sha256.Sum256(module)
		content[locale.Module(l.Name)] = module
		sources[l.Name] = source{version: hex.EncodeToString(sum[:versionBytes]), name: name}
	}

	content[locale.TypeScriptDir+"/dictionaries.ts"] = loaders(c, sources)

	return codegen.Files{Header: Header, Dir: locale.TypeScriptDir, Content: content}, nil
}

func plainText(m icu.Message) (string, bool) {
	var text strings.Builder

	for _, part := range m {
		t, ok := part.(icu.Text)
		if ok == false {
			return "", false
		}

		text.WriteString(string(t))
	}

	return text.String(), true
}

func importPath(file string) string {
	return "@/" + strings.TrimSuffix(strings.TrimPrefix(file, "assets/"), ".ts")
}

func typesImport(name string) string {
	return fmt.Sprintf("import type { %s } from '%s';\n\n", name, importPath(locale.TypeScriptDir+"/types/"+name+".ts"))
}

func params(c dictionaries.Catalog) []byte {
	var b strings.Builder
	b.WriteString(Header + "\n")

	if takesPlural(c.Args) {
		b.WriteString(typesImport("Decimal"))
	}

	b.WriteString("export type MessageParams = {\n")

	for _, key := range c.Keys {
		fmt.Fprintf(&b, "    %s: %s;\n", codegen.Quote(key), paramsOf(c.Args[key]))
	}

	b.WriteString("};\n\nexport type MessageKey = keyof MessageParams;\n")

	return []byte(b.String())
}

func takesPlural(args map[string]map[string]icu.Kind) bool {
	for _, kinds := range args {
		for _, kind := range kinds {
			if kind == icu.KindPlural {
				return true
			}
		}
	}

	return false
}

func paramsOf(kinds map[string]icu.Kind) string {
	if len(kinds) == 0 {
		return "null"
	}

	members := make([]string, 0, len(kinds))
	for _, name := range slices.Sorted(maps.Keys(kinds)) {
		valueType := "string"
		if kinds[name] == icu.KindPlural {
			valueType = "Decimal | number"
		}

		members = append(members, name+": "+valueType)
	}

	return "{ " + strings.Join(members, "; ") + " }"
}

func loaders(c dictionaries.Catalog, sources map[string]source) []byte {
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString(typesImport("DictionarySource"))
	b.WriteString("export const dictionaries: Readonly<Record<string, DictionarySource>> = {\n")

	for _, l := range c.Locales {
		fmt.Fprintf(&b, "    %s: { version: '%s', name: %s, load: async () => (await import('%s')).dictionary },\n", l.Name, sources[l.Name].version, codegen.Quote(sources[l.Name].name), importPath(locale.Module(l.Name)))
	}

	b.WriteString("};\n")

	return []byte(b.String())
}

func dictionary(keys []string, l dictionaries.Locale) []byte {
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString(typesImport("Dictionary"))
	b.WriteString("export const dictionary: Dictionary = {\n")

	for _, key := range keys {
		fmt.Fprintf(&b, "    %s: %s,\n", codegen.Quote(key), message(l.Messages[key]))
	}

	b.WriteString("};\n")

	return []byte(b.String())
}
