// Code generated by tsgen. DO NOT EDIT.

export const AdsConversion = {
    SignUp: 'sign_up',
} as const;

export type AdsConversion = (typeof AdsConversion)[keyof typeof AdsConversion];

export const isAdsConversion = (v: unknown): v is AdsConversion =>
    Object.values(AdsConversion).some((value) => value === v);
