// Code generated by tsgen. DO NOT EDIT.

export const TrackedEvent = {
    SignUp: 'sign_up',
    Login: 'login',
} as const;

export type TrackedEvent = (typeof TrackedEvent)[keyof typeof TrackedEvent];

export const isTrackedEvent = (v: unknown): v is TrackedEvent =>
    Object.values(TrackedEvent).some((value) => value === v);
