package codegen_test

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	"gokick/tools/codegen"
	"gokick/tools/codegen/codegentest"
)

const header = "// Code generated by test. DO NOT EDIT.\n"

func TestWriteWritesWhatChangedAndRemovesOrphans(t *testing.T) {
	root := t.TempDir()
	codegentest.WriteFile(t, root, "assets/same.ts", header+"same\n")
	codegentest.WriteFile(t, root, "assets/old.ts", header+"old\n")
	codegentest.WriteFile(t, root, "assets/hand.ts", "export type Hand = string;\n")
	codegentest.WriteFile(t, root, "other/elsewhere.ts", header+"elsewhere\n")
	files := codegen.Files{Header: header, Dir: "assets", Content: map[string][]byte{
		"assets/new/new.ts": []byte(header + "new\n"),

		"assets/same.ts": []byte(header + "same\n"),
	}}

	changed, err := codegen.Write(root, files)
	if err != nil {
		t.Fatal(err)
	}

	if want := []string{"wrote assets/new/new.ts", "removed assets/old.ts"}; slices.Equal(changed, want) == false {
		t.Errorf("changed %v, want %v", changed, want)
	}

	for _, kept := range []string{"assets/hand.ts", "other/elsewhere.ts"} {
		if _, err := os.Stat(filepath.Join(root, kept)); err != nil {
			t.Errorf("%s is gone: %v", kept, err)
		}
	}

	if changed, err := codegen.Write(root, files); err != nil || len(changed) > 0 {
		t.Errorf("a second run changed %v, %v", changed, err)
	}
}

func TestDriftNamesMissingDifferentAndOrphanFiles(t *testing.T) {
	root := t.TempDir()
	codegentest.WriteFile(t, root, "assets/b.ts", header+"old\n")
	codegentest.WriteFile(t, root, "assets/c.ts", header+"\n")
	codegentest.WriteFile(t, root, "assets/d.ts", header+"same\n")

	found, err := codegen.Drift(root, codegen.Files{Header: header, Dir: "assets", Content: map[string][]byte{
		"assets/a.ts": []byte(header),

		"assets/b.ts": []byte(header + "new\n"),

		"assets/d.ts": []byte(header + "same\n"),
	}})
	if err != nil {
		t.Fatal(err)
	}

	want := []string{"assets/a.ts is missing", "assets/b.ts is out of date", "assets/c.ts is no longer generated"}
	if slices.Equal(found, want) == false {
		t.Errorf("drift %v, want %v", found, want)
	}
}

func TestDriftAcceptsAMissingDirectory(t *testing.T) {
	found, err := codegen.Drift(t.TempDir(), codegen.Files{Header: header, Dir: "assets"})

	if err != nil || len(found) > 0 {
		t.Errorf("drift %v, %v", found, err)
	}
}
