// Code generated by tsgen. DO NOT EDIT.

import { isRecord, isString } from '@/shared/TypeGuards/typeGuards';

export type SignedInUser = {
    id: string;
    locale: string;
};

export const isSignedInUser = (v: unknown): v is SignedInUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['locale']);
