package frontend

import (
	"errors"
	"slices"
	"testing"
	"testing/fstest"
)

func TestFindReadsScriptsAndComponents(t *testing.T) {
	literals, err := Find(fstest.MapFS{
		"assets/app.ts": {Data: []byte("t('app.title');\nconst key = `tracking.${tool}`;")},

		"assets/shared/Dictionary/Locales/cs_CZ.ts": {Data: []byte("// Code generated by i18n. DO NOT EDIT.\nconst m = { 'home.title': 'Úvod' };")},

		"assets/app.css": {Data: []byte(`.x::after { content: 'css.text' }`)},

		"assets/Login.vue": {Data: []byte(`<script setup lang="ts">
const title = t('login.title');
</script>

<template>
    <BaseInput :label="t('form.email')" text-key="form.password" class="flex" />
    <p>{{ t('login.lead') }}</p>
    <BaseInput .title="t('form.name')" />
    <p>{{ count<limit ? t('form.limit') : '' }}</p>
</template>

<style>
.x::after { content: 'style.text' }
</style>
`)},
	}, "assets")
	if err != nil {
		t.Fatal(err)
	}

	want := []Literal{
		{Pos: "assets/Login.vue:1:21", Text: "ts"},
		{Pos: "assets/Login.vue:2:17", Text: "login.title"},
		{Pos: "assets/Login.vue:6:26", Text: "form.email"},
		{Pos: "assets/Login.vue:6:51", Text: "form.password"},
		{Pos: "assets/Login.vue:6:73", Text: "flex"},
		{Pos: "assets/Login.vue:7:13", Text: "login.lead"},
		{Pos: "assets/Login.vue:8:26", Text: "form.name"},
		{Pos: "assets/Login.vue:9:27", Text: "form.limit"},
		{Pos: "assets/Login.vue:9:43", Text: ""},
		{Pos: "assets/app.ts:1:3", Text: "app.title"},
		{Pos: "assets/app.ts:2:13", Text: "tracking.", Built: true},
	}
	if slices.Equal(literals, want) == false {
		t.Errorf("Find =\n%v\nwant\n%v", literals, want)
	}
}

func TestFindRefusesScriptsWithJSX(t *testing.T) {
	for _, name := range []string{"assets/View.tsx", "assets/View.jsx"} {
		if _, err := Find(fstest.MapFS{name: {Data: []byte("<p>{t('a')}</p>")}}, "assets"); errors.Is(err, ErrUnreadable) == false {
			t.Errorf("Find(%s) = %v, want %v", name, err, ErrUnreadable)
		}
	}
}
