package typescript

import (
	"fmt"
	"maps"
	"slices"
	"strings"

	"gokick/tools/tsgen/catalog"
	"gokick/tools/tsgen/gosource"
)

const Header = "// Code generated by tsgen. DO NOT EDIT.\n"

type file struct {
	path string

	module string

	directives map[gosource.TypeRef]catalog.Directive

	names map[string]bool

	imports map[string]map[string]bool

	blocks []string
}

func Render(c catalog.Catalog) (map[string][]byte, error) {
	files := map[string]*file{}

	fileOf := func(dir catalog.Directive) (*file, error) {
		f, ok := files[dir.Path]
		if ok == false {
			f = &file{
				path: dir.Path,

				module: dir.Module(),

				directives: c.Directives,

				names: map[string]bool{},

				imports: map[string]map[string]bool{},
			}
			files[dir.Path] = f
		}

		if err := f.claim(dir.Name); err != nil {
			return nil, err
		}

		return f, nil
	}
	for i := range c.Unions {
		f, err := fileOf(c.Unions[i].Dir)
		if err != nil {
			return nil, err
		}

		f.blocks = append(f.blocks, unionBlock(&c.Unions[i]))
	}

	for i := range c.DTOs {
		f, err := fileOf(c.DTOs[i].Dir)
		if err == nil {
			err = f.addDTO(&c.DTOs[i])
		}

		if err != nil {
			return nil, err
		}
	}

	rendered := make(map[string][]byte, len(files))
	for path, f := range files {
		rendered[path] = f.bytes()
	}

	return rendered, nil
}

func (f *file) claim(name string) error {
	if f.names[name] {
		return fmt.Errorf("%s: %s is defined twice", f.path, name)
	}

	f.names[name] = true

	return nil
}

func (f *file) use(module, specifier string) {
	if module == f.module {
		return
	}

	if f.imports[module] == nil {
		f.imports[module] = map[string]bool{}
	}

	f.imports[module][specifier] = true
}

func (f *file) bytes() []byte {
	var b strings.Builder
	b.WriteString(Header)

	if len(f.imports) > 0 {
		b.WriteString("\n")
	}

	for _, module := range slices.Sorted(maps.Keys(f.imports)) {
		b.WriteString(importLine(module, f.imports[module]))
	}

	for _, block := range f.blocks {
		b.WriteString("\n" + block)
	}

	return []byte(b.String())
}

func importLine(module string, specifiers map[string]bool) string {
	names := slices.SortedFunc(maps.Keys(specifiers), func(a, b string) int {
		return strings.Compare(strings.TrimPrefix(a, "type "), strings.TrimPrefix(b, "type "))
	})

	values := slices.ContainsFunc(names, func(name string) bool { return strings.HasPrefix(name, "type ") == false })
	if values {
		return fmt.Sprintf("import { %s } from '%s';\n", strings.Join(names, ", "), module)
	}

	for i, name := range names {
		names[i] = strings.TrimPrefix(name, "type ")
	}

	return fmt.Sprintf("import type { %s } from '%s';\n", strings.Join(names, ", "), module)
}
