// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, locale) VALUES (lower($1), $2, $3) RETURNING id, email, password_hash, created_at, locale
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Locale       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Locale,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const emailByID = `-- name: EmailByID :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) EmailByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, emailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const updateLocale = `-- name: UpdateLocale :exec
UPDATE users SET locale = $1 WHERE id = $2
`

type UpdateLocaleParams struct {
	Locale string
	ID     uuid.UUID
}

func (q *Queries) UpdateLocale(ctx context.Context, arg UpdateLocaleParams) error {
	_, err := q.db.Exec(ctx, updateLocale, arg.Locale, arg.ID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, created_at, locale FROM users WHERE email = lower($1)
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Locale,
	)
	return i, err
}
