// Code generated by tsgen. DO NOT EDIT.

import { isNumber, isRecord } from '@/shared/TypeGuards/typeGuards';

export type EndedSessions = {
    ended: number;
};

export const isEndedSessions = (v: unknown): v is EndedSessions =>
    isRecord(v)
    && isNumber(v['ended']);
