// Code generated by tsgen. DO NOT EDIT.

import { isBoolean, isRecord, isString, nullable } from '@/shared/TypeGuards/typeGuards';

export type ListedSession = {
    id: string;
    userAgent: string;
    createdAt: string;
    lastSeenAt: string;
    lastSeenIp: string | null;
    current: boolean;
};

export const isListedSession = (v: unknown): v is ListedSession =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['userAgent'])
    && isString(v['createdAt'])
    && isString(v['lastSeenAt'])
    && nullable(isString)(v['lastSeenIp'])
    && isBoolean(v['current']);
