// Code generated by tsgen. DO NOT EDIT.

import { isApiFieldErrors } from '@/shared/Fetch/Envelope/ApiFieldErrors';
import type { ApiMessage } from '@/shared/Fetch/Envelope/ApiMessage';

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginRequestErrors = {
    general?: ApiMessage;
    email?: ApiMessage;
    password?: ApiMessage;
};

export const isLoginRequestErrors = (v: unknown): v is LoginRequestErrors =>
    isApiFieldErrors(/^(?:general|email|password)$/, v);
