// Code generated by tsgen. DO NOT EDIT.

import { isApiFieldErrors } from '@/shared/Fetch/Envelope/ApiFieldErrors';
import type { ApiMessage } from '@/shared/Fetch/Envelope/ApiMessage';

export type RegisterRequest = {
    email: string;
    password: string;
    locale: string;
};

export type RegisterRequestErrors = {
    general?: ApiMessage;
    email?: ApiMessage;
    password?: ApiMessage;
    locale?: ApiMessage;
};

export const isRegisterRequestErrors = (v: unknown): v is RegisterRequestErrors =>
    isApiFieldErrors(/^(?:general|email|password|locale)$/, v);
