// Code generated by i18n. DO NOT EDIT.

import type { Decimal } from '@/shared/I18n/Dictionary/types/Decimal';
import type { Message } from '@/shared/I18n/Dictionary/types/Message';

export type NumberSample = readonly [Decimal | number, string];

export const message: Message = [{ type: 'plural', name: 'n', offset: 0, exact: {}, cases: { zero: ['zero ', { type: 'pound' }], one: ['one ', { type: 'pound' }], two: ['two ', { type: 'pound' }], few: ['few ', { type: 'pound' }], many: ['many ', { type: 'pound' }], other: ['other ', { type: 'pound' }] } }];
